### ISSUE TITLE
Fix Schema

### ISSUE THREAD

**Issue by gabikeane** [gabikeane/VictGhostStories#3]
So after doing yet more markup, I've discovered that the schema doesn't allow for the p tags after the plot tag, instead requiring either another plot element or an end tag.  I've tried all the iterations of the repeatable or-group I know of.  I'll also be posting in the discussion forum as well (and hopefully David or Shannen will answer), but I figured I'd post it here first.
I'll be updating the schema with my newest version now, so we sync yours before you start working.

**Comment by djbpitt** [comment]
Your schema line reads:

body = element body { plot\* | chapter? | p+ }

This says that you can have zero or more <plot> elements or one or more
<chapter> elements or one or more <p> elements, but no matter which of
those you choose, you can have only one type of element inside a <body>.
That means that if you start with a <plot> element, as you do in the
Charrington file, all you can have are more <plot> elements. Can you tell
us in prose what you'd like to be allowed inside <body>?
